version: '3.9'

services:
 
  api-server:
    build: .
    image: api-server:${GIT_SHA:-latest}
    networks:
      api_network:
    ports:
      - "8000:8000"

  nginx:
    image: nginx:1.25.3
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - api_network
    ports:
      - "80:80"

  # POSTGRES DEFINITION
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=todo_app
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=pass2
    ports:
      - "5436:5432"
    deploy:
      resources:
        limits:
          memory: 4g
    networks:
      api_network:


  pgadmin:
    image: dpage/pgadmin4:6.4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8085:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      api_network:

networks:
  api_network:

volumes:
  postgres:
  pgadmin:

